#!/usr/bin/env python3
"""
Simple Dashboard Updater

This script takes Claude's report (as plain text) and helps you update the dashboard.
No parsing, no GitHub API - just simple file updates with your input.

Usage:
    python3 simple_update.py

The script will ask you for:
- Release version (e.g., 4.34.0)
- Week date (e.g., February 3, 2026)
- Risk level (e.g., MEDIUM-HIGH)
- Number of P0 items
- Number of medium risk items
- Number of zero risk areas

Then it will:
- Update index.html with the summary
- Create a blank report page for you to fill in
- Update reports/index.html with a new entry

You'll still need to manually paste Claude's content into the report page,
but this handles the tedious parts (dates, links, counts, etc.)
"""

import re
from datetime import datetime
from pathlib import Path


def get_input_with_default(prompt: str, default: str = None) -> str:
    """Get user input with optional default value"""
    if default:
        result = input(f"{prompt} [{default}]: ").strip()
        return result if result else default
    return input(f"{prompt}: ").strip()


def update_main_dashboard(version: str, week_of: str, risk_level: str, p0_count: int, 
                          medium_count: int, zero_count: int, report_date: str):
    """Update index.html with new summary data"""
    
    print("\n📝 Updating index.html...")
    
    index_path = Path('index.html')
    if not index_path.exists():
        print("   ❌ index.html not found!")
        return False
    
    content = index_path.read_text()
    
    # Update risk level
    risk_class = f'risk-{risk_level.lower().replace("-", "")}'
    content = re.sub(
        r'<span class="risk-level risk-\w+">[^<]+</span>',
        f'<span class="risk-level {risk_class}">{risk_level}</span>',
        content,
        count=1
    )
    
    # Update version and date
    content = re.sub(
        r'<strong>Android RC [\d.]+</strong> • Week of [^<]+',
        f'<strong>Android RC {version}</strong> • Week of {week_of}',
        content,
        count=1
    )
    
    # Update P0 count
    content = re.sub(
        r'<div class="stat-mini-value" style="color: #d44c47;">\d+</div>\s*<div class="stat-mini-label">P0 Items',
        f'<div class="stat-mini-value" style="color: #d44c47;">{p0_count}</div>\n                        <div class="stat-mini-label">P0 Items',
        content,
        count=1
    )
    
    # Update medium risk count
    content = re.sub(
        r'<div class="stat-mini-value" style="color: #cb912f;">\d+</div>\s*<div class="stat-mini-label">Medium Risk',
        f'<div class="stat-mini-value" style="color: #cb912f;">{medium_count}</div>\n                        <div class="stat-mini-label">Medium Risk',
        content,
        count=1
    )
    
    # Update zero risk count
    content = re.sub(
        r'<div class="stat-mini-value" style="color: #448361;">\d+</div>\s*<div class="stat-mini-label">Zero Risk',
        f'<div class="stat-mini-value" style="color: #448361;">{zero_count}</div>\n                        <div class="stat-mini-label">Zero Risk',
        content,
        count=1
    )
    
    # Update "View Full Report" link
    content = re.sub(
        r'<a href="reports/[\d-]+\.html" class="view-full-report">',
        f'<a href="reports/{report_date}.html" class="view-full-report">',
        content,
        count=1
    )
    
    # Update footer timestamp
    timestamp = datetime.now().strftime("%B %d, %Y at %I:%M %p PST")
    content = re.sub(
        r'<span class="last-updated">Last Updated:</span> [^•]+',
        f'<span class="last-updated">Last Updated:</span> {timestamp}',
        content
    )
    
    index_path.write_text(content)
    print("   ✅ index.html updated!")
    return True


def create_blank_report(version: str, week_of: str, risk_level: str, report_date: str):
    """Create a new report page from template"""
    
    print(f"\n📄 Creating reports/{report_date}.html...")
    
    template_path = Path('report-template.html')
    if not template_path.exists():
        print("   ❌ report-template.html not found!")
        return False
    
    report_path = Path(f'reports/{report_date}.html')
    report_path.parent.mkdir(exist_ok=True, parents=True)
    
    content = template_path.read_text()
    
    # Update version and dates
    content = content.replace('Android RC 4.33.0', f'Android RC {version}')
    content = content.replace('Jan 27, 2026', week_of.split(',')[0].strip() + ', 2026')
    content = content.replace('January 27, 2026', week_of)
    
    # Update risk level
    risk_class = f'risk-{risk_level.lower().replace("-", "")}'
    content = re.sub(
        r'<div class="risk-badge risk-\w+">.*?</div>',
        f'<div class="risk-badge {risk_class}">⚠️ {risk_level} RISK</div>',
        content,
        count=1
    )
    
    # Update footer
    timestamp = datetime.now().strftime("%B %d, %Y at %I:%M %p PST")
    content = re.sub(
        r'Generated by Claude AI • [^<]+<br>',
        f'Generated by Claude AI • {timestamp}<br>',
        content
    )
    content = re.sub(
        r'Report ID: Android RC [\d.]+',
        f'Report ID: Android RC {version}',
        content
    )
    
    report_path.write_text(content)
    print(f"   ✅ Report page created!")
    print(f"   📝 Now open reports/{report_date}.html and paste Claude's content into the sections")
    return True


def update_report_history(version: str, week_of: str, risk_level: str, report_date: str, 
                          p0_count: int, medium_count: int, summary: str):
    """Add new entry to reports/index.html"""
    
    print(f"\n📋 Updating reports/index.html...")
    
    history_path = Path('reports/index.html')
    if not history_path.exists():
        print("   ❌ reports/index.html not found!")
        return False
    
    content = history_path.read_text()
    
    risk_class = f'risk-{risk_level.lower().replace("-", "")}'
    
    # Create new report card
    new_card = f'''
            <!-- Week of {week_of} -->
            <a href="{report_date}.html" class="report-card">
                <div class="report-header">
                    <div class="report-title">📱 Android RC {version}</div>
                    <span class="risk-badge {risk_class}">{risk_level}</span>
                </div>
                <div class="report-meta">
                    Week of {week_of} • {p0_count} P0 items, {medium_count} notable changes
                </div>
                <div class="report-summary">
                    {summary}
                </div>
            </a>
'''
    
    # Insert at top of report list
    content = re.sub(
        r'(<div class="report-list">)',
        f'\\1{new_card}',
        content,
        count=1
    )
    
    history_path.write_text(content)
    print("   ✅ reports/index.html updated!")
    return True


def main():
    print("=" * 70)
    print("📊 SIMPLE DASHBOARD UPDATER")
    print("=" * 70)
    print("\nThis script helps you update the dashboard with Claude's report.")
    print("You'll need to manually paste Claude's content into the report page.\n")
    
    # Get inputs
    print("📝 Enter the details from Claude's report:\n")
    
    version = get_input_with_default("Release version (e.g., 4.34.0)", "4.34.0")
    week_of = get_input_with_default("Week of (e.g., February 3, 2026)", datetime.now().strftime("%B %d, %Y"))
    risk_level = get_input_with_default("Risk level (e.g., MEDIUM-HIGH)", "MEDIUM").upper()
    
    p0_count = int(get_input_with_default("Number of P0 items", "5"))
    medium_count = int(get_input_with_default("Number of medium risk items (Other Notable Changes)", "4"))
    zero_count = int(get_input_with_default("Number of zero risk areas", "6"))
    
    summary = get_input_with_default("Brief summary for history (1-2 sentences)", 
                                     "UI redesigns and core flow changes")
    
    # Generate report date
    report_date = datetime.now().strftime('%Y-%m-%d')
    custom_date = input(f"Report date (YYYY-MM-DD) [{report_date}]: ").strip()
    if custom_date:
        report_date = custom_date
    
    print("\n" + "=" * 70)
    print("📊 SUMMARY")
    print("=" * 70)
    print(f"Version:      Android RC {version}")
    print(f"Week:         {week_of}")
    print(f"Risk Level:   {risk_level}")
    print(f"P0 Items:     {p0_count}")
    print(f"Medium Risk:  {medium_count}")
    print(f"Zero Risk:    {zero_count}")
    print(f"Report Date:  {report_date}")
    print("=" * 70)
    
    confirm = input("\n✅ Does this look correct? (y/n): ").strip().lower()
    if confirm != 'y':
        print("❌ Cancelled.")
        return
    
    print("\n🚀 Updating files...\n")
    
    # Update files
    success = True
    success &= update_main_dashboard(version, week_of, risk_level, p0_count, 
                                     medium_count, zero_count, report_date)
    success &= create_blank_report(version, week_of, risk_level, report_date)
    success &= update_report_history(version, week_of, risk_level, report_date, 
                                     p0_count, medium_count, summary)
    
    if success:
        print("\n" + "=" * 70)
        print("✅ DASHBOARD UPDATED!")
        print("=" * 70)
        print(f"\n📝 Next Steps:")
        print(f"   1. Open reports/{report_date}.html in a text editor")
        print(f"   2. Paste Claude's content into each section:")
        print(f"      - Overall Risk Level summary (3 bullets)")
        print(f"      - P0 items (replace the example items)")
        print(f"      - Other Notable Changes (replace the examples)")
        print(f"      - No Code Changes (replace the text)")
        print(f"   3. Save the file")
        print(f"   4. Review:")
        print(f"      - Open index.html in browser to check summary")
        print(f"      - Open reports/{report_date}.html in browser to check details")
        print(f"   5. Commit and push:")
        print(f"      git add .")
        print(f"      git commit -m 'Weekly update: {week_of} - Android RC {version}'")
        print(f"      git push")
        print(f"\n🌐 Dashboard will update at:")
        print(f"   https://tiffanyliang-speak.github.io/risk-dashboard/")
    else:
        print("\n❌ Some files failed to update. Check the errors above.")


if __name__ == "__main__":
    main()
